### PR TITLE
card_from_chars now supports lowercase faces

### PR DESCRIPTION
**Pull request by ydm**

### CODE REVIEW

**Comment by b-inary** [comment]
I can merge this PR, but on second thought, I should refactor the code to move `flop_from_str`, `card_from_str`, and `card_from_chars` from `game.rs` to `range.rs`.

As for the content of the PR, I think we need to define a policy on how to handle upper and lower case letters. The current policy follows GTO+: only accepts uppercase ranks, lowercase suits, and lowercase suitedness. On the contrary, PioSOLVER is case-insensitive. This PR lies in the middle of these. Could you give me your opinion about which policy is preferable?

**Comment by ydm** [comment]
I honestly think, since there's no ambiguity in distinguishing ranks and suits, it's OK to make it case-insensitive. But I believe in your judgement and it's perfectly good to follow the capital-rank-lower-suit convention.

**Comment by b-inary** [comment]
`range.rs` was now refactored. Now `card_from_chars()` calls `char_to_rank()`, so by modifying `char_to_rank()` and `COMBO_PAT`, we can support lowercase ranks in `card_from_chars()` as well as range strings (some test cases also need to be modified). I'm sorry but if you want to continue this topic, please modify the commit or resubmit the PR.

Now I'm beginning to think that just accepting lowercase ranks is a good idea (accepting uppercase suit/suitedness is too much). I will merge the PR if you would modify the commit.

**Comment by b-inary** [comment]
Now lowercase rank characters are supported (865b18a).

**Pull request closed without merging**
